# configs/global/models.yaml
models:
  qwen3_vl_8b:
    root: models
    relpath: Qwen3.5-VL-8B-Instruct

  qwen3_vl_8b_thinking:
    root: models
    relpath: Qwen3.5-VL-8B-Thinking

  qwen3_5_4b:
    root: models
    relpath: Qwen3.5-4B

  qwen3_5_9b:
    root: models
    relpath: Qwen3.5-9B
